:memo: Add scene parser
epitech-mirroring/RTX pull request #40
Opened 2024-05-02 18:47 UTC by Quentintnrl

Remove all math lib
Use the GLM math lib
Parse the scene file

2024-05-02 19:47 UTC, RenardFute requested changes
Please rename your files and classes. Also, I'm not a big fan of your implementation of the factory. The design pattern you tried to implement actually requires instantiating a factory, fill it and then use it to create an object. It is not supposed to be prefilled and only have static access.

2024-05-02 19:47 UTC, RenardFute commented on include/primitives/Properties/abstractProperties.hpp
> +class abstractProperties {
Please use PascalCase

2024-05-02 19:47 UTC, RenardFute commented on include/primitives/Properties/cubeProperties.hpp
> +class cubeProperties : public abstractProperties {
Please use PascalCase

2024-05-02 19:47 UTC, RenardFute commented on include/primitives/objectsFactory.hpp
> +    static Object createObject(JsonObject *obj);
I think your factory is missing some functions like ``void registerObject(std::string name, std::function<Object(AbstractPropersties)> creator)``

2024-05-02 19:47 UTC, RenardFute commented on src/primitives/objectsFactory.cpp
Please use CamelCase in your file names

2024-05-02 19:47 UTC, RenardFute commented on tests/testsSceneParser.cpp
> +#define TEST_JSON "scenes/tests/test.json"
Not a good practices since it's not the only file use in this tests

2024-05-02 19:49 UTC, aimericdrk approved these changes

2024-05-03 00:13 UTC, RenardFute requested changes
Good in the overall, just move the factories' registers outside their constructors.
Also can you try to keep the indices and vertices outside the properties, the properties class will be full enough no need to make it messier with all the vertices data

2024-05-03 00:13 UTC, RenardFute commented on include/primitives/Properties/CubeProperties.hpp
> +        CubeProperties() { _size = 1; };
You should call the super constructor

2024-05-03 01:15 UTC, RenardFute approved these changes
Fine for me 👌

2024-05-03 01:30 UTC, RenardFute approved these changes

2024-05-03 01:31 UTC, merged