:twisted_rightwards_arrows: Merging the objFile loader
epitech-mirroring/RTX pull request #44
Opened 2024-05-05 15:54 UTC by aimericdrk

2024-05-05 16:06 UTC, RenardFute requested changes
You have deleted way too many files, please check this.

I'm also not a big fan of the library name, something like "libobj.so" would have been better in my opinion but whatever.

This is not mandatory, but would it be possible to add unit tests for this library ?

2024-05-05 16:06 UTC, RenardFute commented on parser/objFile/src/myObjParser.cpp
> +std::vector<std::string> split(const std::string &s, char delimiter) {
can you put this function as static

2024-05-05 16:06 UTC, RenardFute commented on parser/objFile/src/myObjParser.cpp
> +glm::vec3 parseVec3(const std::string& line) {
can you also put this function as static

2024-05-05 16:06 UTC, RenardFute commented on parser/objFile/src/myObjParser.cpp
> +}
Please add the missing trailing line

```suggestion
}

```

2024-05-05 16:06 UTC, RenardFute commented on parser/objFile/src/myObjParser.cpp
Would have been better if the big parse file was subdivided in smaller functions (i.e. parseNormal, parseVertex etc…)

2024-05-05 16:10 UTC, aimericdrk commented on .github/ISSUE_TEMPLATE/add-task.md
i don't know how i did this

2024-05-05 16:11 UTC, aimericdrk commented on Makefile
> -CXXFLAGS		= 	-W -Wall -Wextra -std=c++20 --coverage -I./include  \
sry used this to debug and code faster ig

2024-05-05 16:11 UTC, RenardFute commented
I just realized, but this is missing all the abstract class part and everything that should allow the scene parser to call a file parser, can you fix this please.

2024-05-05 16:19 UTC, aimericdrk commented on parser/objFile/src/myObjParser.cpp
sry but for the moment ( i'm talking about the fact that the texture arn't taken in account ) it will be easier to do it like this + for optimisation doing it like this is slightly more optimised ( for .obj with 50 000 faces you see the difference )

2024-05-05 16:23 UTC, RenardFute commented on parser/objFile/src/myObjParser.cpp
I'm not sure about efficiency but letting it like that can only create debt.

2024-05-05 16:24 UTC, Quentintnrl commented on assets/objFiles/chair/Chair Version 2 mm.mtl
Add underscores to the file name

2024-05-05 16:25 UTC, Quentintnrl commented on assets/objFiles/chair/Chair Version 2 mm.obj
Same here

2024-05-05 16:25 UTC, Quentintnrl commented on assets/objFiles/chair/Chair Version 2 mm_1.jpg
Same here

2024-05-05 16:25 UTC, Quentintnrl commented on assets/objFiles/godzilla/Godzilla 2019 Color V2 mm.mtl
Same here

2024-05-05 16:25 UTC, Quentintnrl commented on assets/objFiles/godzilla/Godzilla 2019 Color V2 mm.obj
Same here

2024-05-05 16:25 UTC, Quentintnrl commented on assets/objFiles/godzilla/Godzilla 2019 Color V2 mm_1.jpg
Same here

2024-05-05 16:25 UTC, RenardFute commented
Also, @aimericdrk FYI you're not passing Jenkins checks because the main Makefile assume the name of lib should be ``libObjParser.so`` and not ``libobjParser.so`` you should fix this in your lib's Makefile

2024-05-05 16:26 UTC, RenardFute commented on assets/objFiles/chair/Chair Version 2 mm.mtl
I thin why he means is to replace spaces by underscore

2024-05-05 16:39 UTC, Quentintnrl requested changes
Look at the different comments

2024-05-05 16:47 UTC, aimericdrk commented
> Look at the different comments

2024-05-07 13:46 UTC, RenardFute requested changes

2024-05-07 13:46 UTC, RenardFute commented on include/abstractParser.hpp
> +class abstractParser {
Please use pascal case in the class name and file name

2024-05-07 13:46 UTC, RenardFute commented on include/abstractParser.hpp
> +};
Add missing trailing line
```suggestion
};

```

2024-05-07 13:46 UTC, RenardFute commented on parser/objFile/include/objParser/objParser.hpp
> +class objParser : public abstractParser {
Please use PascalCase in the class name and file name

2024-05-07 13:46 UTC, RenardFute commented on parser/objFile/include/objParser/objParser.hpp
> +        Object *parseFile(const std::string& filename);
I think your functions are missing the override flag.

2024-05-07 14:23 UTC, RenardFute approved these changes

2024-05-07 14:26 UTC, merged