41 ice cube rectangle shape
epitech-mirroring/RTX pull request #45
Opened 2024-05-05 20:40 UTC by Quentintnrl

Add the rectangle shape parsing

2024-05-05 21:47 UTC, RenardFute requested changes
Good in the overall, can you just remove the debugs and comments ?

2024-05-05 21:47 UTC, RenardFute commented on Makefile
> +CXXFLAGS		= 	-g -W -Wall -Wextra -std=c++20 --coverage -I./include  \
Why adding a debug flag ?

2024-05-05 21:47 UTC, RenardFute commented on include/SceneParser.hpp
> +        void setPath(std::string path);
Why did you change that ? Passing path by reference seems alright

2024-05-05 21:47 UTC, RenardFute commented on include/primitives/Properties/PropertiesFactory.hpp
> +#include "primitives/Properties/RectangleProperties.hpp"
Is this include really needed ?

2024-05-05 21:47 UTC, RenardFute commented on shaders/raytracing.frag
> +    iNumSpheres = iNumTriangles * 3;
can you remove this debug please ?

2024-05-05 21:47 UTC, RenardFute commented on shaders/raytracing.frag
> +    FragColor = hit.hit ? vec4(hit.normal, 1.0) : vec4(ray.direction, 1.0);
when nothing is hit it should be black can you revert that ?

2024-05-05 21:47 UTC, RenardFute commented on src/Scene.cpp
> +//    for (auto & _object : _objects) {
? Remove or uncomment, but don't let it like that ?

2024-05-05 21:47 UTC, RenardFute commented on src/main.cpp
> +//            scene.getCameras().at(0).getTransform().rotate({0.0f, 1.0f, 0.0f}, 0.05f);
Can you remove this please ?

2024-05-05 21:47 UTC, RenardFute commented on src/primitives/Rectangle.cpp
> +static std::vector<Triangle> generateTriangles(const RectangleProperties &properties)
Passing the properties class seems a bit too much, can't you just pass 3 values ?

2024-05-06 12:20 UTC, RenardFute approved these changes

2024-05-06 16:43 UTC, aimericdrk commented on include/primitives/Cube.hpp
> +    float getSize() const { return _properties.getSize(); }
even if it's one line coding you shouldn't code in hpp

2024-05-06 16:43 UTC, aimericdrk commented on include/primitives/Cube.hpp
> +    float &getSize() { return _properties.getSize(); }
same as previous

2024-05-06 16:43 UTC, aimericdrk commented on include/primitives/Properties/CubeProperties.hpp
> +    CubeProperties() : AbstractProperties() { _size = 1.0; };
replace _size = 1.0 by 1.0f to force the type as a float ( 1.0 is a double )

2024-05-06 16:43 UTC, aimericdrk commented on include/primitives/Properties/CubeProperties.hpp
> +    void setSize(float size) { _size = size; }
coding in hpp

2024-05-06 16:43 UTC, aimericdrk commented on include/primitives/Properties/RectangleProperties.hpp
> +** No file there , just an epitech header example .
incorrect header

2024-05-06 16:43 UTC, aimericdrk commented on include/primitives/Properties/RectangleProperties.hpp
> +        RectangleProperties() : AbstractProperties() { _length = 1; _width = 1; _height = 1; };
_length = 1.0f; _width = 1.0f; _height = 1.0f;

2024-05-06 16:43 UTC, aimericdrk commented on include/primitives/Rectangle.hpp
> +** No file there , just an epitech header example .
header

2024-05-06 16:43 UTC, aimericdrk commented on scenes/tests/sceneRectangle.json
> +  "cameras": [
why camera is in plural ? ( you can ignore if it isn't revealant )

2024-05-06 16:43 UTC, aimericdrk commented on src/main.cpp
> +    parser.parse();
couldn't you create a function that does this by default ? 
what i mean is that parser.parse() feel useless

2024-05-06 16:43 UTC, aimericdrk commented on src/primitives/Rectangle.cpp
> +** No file there , just an epitech header example .
header

2024-05-06 16:43 UTC, aimericdrk commented on src/primitives/Rectangle.cpp
> +    triangle.normalV0 = {0, 0, -1};
i will put it only once but value should be 0.0f, 0.0f, -1.0f ...

2024-05-06 16:43 UTC, aimericdrk commented on src/primitives/Rectangle.cpp
> +Rectangle::Rectangle(const Material& material, const Transform& transform, const std::vector<Texture>& textures, const RectangleProperties & properties) : Object(material, transform, generateTriangle
why did sometime you return to the new line after the : Object and sometime not
here you don't return

2024-05-06 16:43 UTC, aimericdrk commented on src/primitives/Rectangle.cpp
> + : Object(other) {
here you return

2024-05-06 16:43 UTC, aimericdrk commented on src/primitives/Rectangle.cpp
> +Rectangle::Rectangle(RectangleProperties &properties): Object(properties)
missing space ) : Object

2024-05-06 16:43 UTC, aimericdrk commented on tests/testsSceneParser.cpp
> +    objFactory.registerObject("rectangle", [](AbstractProperties &properties) -> Object * {return new Rectangle(dynamic_cast<RectangleProperties &>(properties));});
asterisk symbol has to be sticked to what's it is pointing to

2024-05-06 16:48 UTC, aimericdrk commented on src/primitives/Cube.cpp
>      // Triangle struct is
yes ?

2024-05-06 18:17 UTC, RenardFute commented on include/primitives/Properties/RectangleProperties.hpp
> +** No file there , just an epitech header example .
Those are all over the place, if the name of the project is good and the description is not just pasted from somewhere else I think we can let it go.

2024-05-06 18:18 UTC, RenardFute commented on scenes/tests/sceneRectangle.json
> +  "cameras": [
We decided to allow multiple cameras for one scene so we can switch programmatically

2024-05-06 18:21 UTC, RenardFute commented on src/main.cpp
> +    parser.parse();
I get what you're saying, 3 line just to parse could have been merge in one or two like.

Old: 
```C++
 SceneParser parser = SceneParser(path, propFactory, objFactory);
 parser.parse();
 Scene scene = parser.getScene();
```  
<br>
What it can be:

```C++
 SceneParser parser = SceneParser(path, propFactory, objFactory);
 Scene scene = parser.parse();
```
or 
```C++
 Scene scene = SceneParser(path, propFactory, objFactory).parse();
```

This is a good idea but I think it should be done in a new issue, @aimericdrk can I let you create it ?

2024-05-07 08:13 UTC, aimericdrk approved these changes

2024-05-07 08:59 UTC, merged