:black_circle:  sphere primitive
epitech-mirroring/RTX pull request #46
Opened 2024-05-07 06:55 UTC by Quentintnrl

Add sphere primitives

2024-05-07 08:30 UTC, aimericdrk commented on include/primitives/Properties/SphereProperties.hpp
> +        SphereProperties() : AbstractProperties() { _radius = 1; };
coding in hpp + _radius = 1.0f

2024-05-07 08:30 UTC, aimericdrk commented on shaders/raytracing.frag
> +//            if (j == 0) {
remove comment + if you have to use it you just can do if (!j)

2024-05-07 08:30 UTC, aimericdrk commented on src/main.cpp
> +    objectsFactory.registerObject("sphere", [](AbstractProperties &properties) -> Object * {
asterix has to be sticked to what's it's pointing to

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +Sphere::Sphere(const Sphere &other)  : Object(other) {
two space before the :

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +Sphere::Sphere(SphereProperties &properties): Object(properties)
missing space before :

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +//    std::vector<glm::vec3> vertices;
comment inside a function

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +
use 1 line separator instead of 2

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +    float j = -r + (float)sqrt(2 * pow(r, 2) * 3);
sqrt(pow(r, 2) * 6); ?

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +    glm::vec3 top = {0, -r, 0};
0.0f to force float type i will leave only one comment about this but do it everywhere

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +        auto x = (float)cos(theta * ((double)i + 2 * M_PI / 10));
2 * M_PI / 10  = M_PI / 5

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +        auto z = (float)sin(theta * ((double)i + 2 * M_PI / 10));
same

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +    std::vector<Triangle> triangles;
remember to declare your vars on the top of the file

2024-05-07 08:30 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +    for (auto & t : triangles) {
remove space between & and t

2024-05-07 08:45 UTC, aimericdrk commented on src/primitives/Sphere.cpp
> +    float theta = 2 * M_PI / 5;
2 * M_PI / 5; = M_PI / 2.5;

2024-05-07 12:46 UTC, RenardFute requested changes

2024-05-07 12:46 UTC, RenardFute commented on shaders/raytracing.frag
> +                Triangle tri = iTriangles[j];
Can you remove this indentation please ?

2024-05-07 12:46 UTC, RenardFute commented on shaders/raytracing.frag
> +    FragColor = hit.hit ? vec4(hit.normal, 1.0) : vec4(255.0, 255.0, 255.0, 1.0);
can you put it back black ?

2024-05-07 12:46 UTC, RenardFute commented on src/main.cpp
I think you might want to keep the cube in the factory as well as the sphere

2024-05-07 13:59 UTC, aimericdrk approved these changes

2024-05-09 16:16 UTC, RenardFute approved these changes

2024-05-09 16:16 UTC, merged